# Generated by Django 3.1.5 on 2021-01-14 20:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Z]?[a-z]*$', message='First name is compulsory and should contain only letters, and no spaces')])),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]?[a-z]*$', message='Last name should contain only letters, and no spaces')])),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^(\\+91|0|91)?[6789]([0-9]{9})$')])),
                ('display_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to=main.models.get_dp_path)),
                ('date_of_birth', models.DateField()),
                ('is_premium', models.BooleanField(default=False)),
                ('profile_summary', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('media', models.FileField(null=True, upload_to=main.models.get_media_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.useraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('like', 'like'), ('share', 'share'), ('post', 'post'), ('report', 'report')], max_length=10)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.useraccount')),
                ('sent_to', models.ManyToManyField(related_name='sent_to', to='main.UserAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accepted', models.BooleanField(default=False)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.useraccount')),
                ('users', models.ManyToManyField(related_name='USERS', to='main.UserAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
