# Generated by Django 3.1.5 on 2021-01-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210115_0250'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='checked',
        ),
    ]
