# Generated by Django 3.1.5 on 2021-01-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20210121_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent_to',
            field=models.ManyToManyField(related_name='notifications', to='main.UserAccount'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useraccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
