# Generated by Django 3.1.5 on 2021-01-25 15:43

from django.db import migrations
import django_resized.forms
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210125_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='display_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='/home/himanshu/Code/sconnect/backend/static/images/default_dp.png', force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to=main.models.get_dp_path),
        ),
    ]
