# Generated by Django 3.1.5 on 2021-01-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_postinteraction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postinteraction',
            unique_together={('user', 'post')},
        ),
    ]
