# Generated by Django 3.1.5 on 2021-02-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210126_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postinteraction',
            options={'verbose_name': 'Post Interaction'},
        ),
    ]
